In [94]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import os

import numpy as np

In [95]:
import warnings
warnings.filterwarnings('ignore')

In [96]:
d1=pd.read_csv('train.csv')
d1.head()

Severity  Safety_Score  \
0                Minor_Damage_And_Injuries     49.223744   
1                Minor_Damage_And_Injuries     62.465753   
2        Significant_Damage_And_Fatalities     63.059361   
3  Significant_Damage_And_Serious_Injuries     48.082192   
4        Significant_Damage_And_Fatalities     26.484018   

   Days_Since_Inspection  Total_Safety_Complaints  Control_Metric  \
0                     14                       22       71.285324   
1                     10                       27       72.288058   
2                     13                       16       66.362808   
3                     11                        9       74.703737   
4                     13                       25       47.948952   

   Turbulence_In_gforces  Cabin_Temperature  Accident_Type_Code  \
0               0.272118              78.04                   2   
1               0.423939              84.54                   2   
2               0.322604              78.86                   7   
3               0.337029              81.79                   3   
4               0.541140              77.16                   3   

   Max_Elevation  Violations  Adverse_Weather_Metric  Accident_ID  
0   31335.476824           3                0.424352         7570  
1   26024.711057           2                0.352350        12128  
2   39269.053927           3                0.003364         2181  
3   42771.499200           1                0.211728         5946  
4   35509.228515           2                0.176883         9054

In [97]:
test=pd.read_csv('test.csv')
test.head()

Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0     19.497717                     16                        6   
1     58.173516                     15                        3   
2     33.287671                     15                        3   
3      3.287671                     21                        5   
4     10.867580                     18                        2   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       72.151322               0.388959              78.32   
1       64.585232               0.250841              78.60   
2       64.721969               0.336669              86.96   
3       66.362808               0.421775              80.86   
4       56.107566               0.313228              79.22   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   4   37949.724386           2                0.069692   
1                   7   30194.805567           2                0.002777   
2                   6   17572.925484           1                0.004316   
3                   3   40209.186341           2                0.199990   
4                   2   35495.525408           2                0.483696   

   Accident_ID  
0            1  
1           10  
2           14  
3           17  
4           21

In [16]:
d1.shape

(10000, 12)

In [35]:
test.shape

(2500, 11)

In [28]:
d1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
Severity                   10000 non-null object
Safety_Score               10000 non-null float64
Days_Since_Inspection      10000 non-null int64
Total_Safety_Complaints    10000 non-null int64
Control_Metric             10000 non-null float64
Turbulence_In_gforces      10000 non-null float64
Cabin_Temperature          10000 non-null float64
Accident_Type_Code         10000 non-null int64
Max_Elevation              10000 non-null float64
Violations                 10000 non-null int64
Adverse_Weather_Metric     10000 non-null float64
Accident_ID                10000 non-null int64
dtypes: float64(6), int64(5), object(1)
memory usage: 937.6+ KB


In [37]:
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
Safety_Score               2500 non-null float64
Days_Since_Inspection      2500 non-null int64
Total_Safety_Complaints    2500 non-null int64
Control_Metric             2500 non-null float64
Turbulence_In_gforces      2500 non-null float64
Cabin_Temperature          2500 non-null float64
Accident_Type_Code         2500 non-null int64
Max_Elevation              2500 non-null float64
Violations                 2500 non-null int64
Adverse_Weather_Metric     2500 non-null float64
Accident_ID                2500 non-null int64
dtypes: float64(6), int64(5)
memory usage: 214.9 KB


In [19]:
d1['Severity'].values

10000

In [20]:
d1['Severity'].value_counts()

Highly_Fatal_And_Damaging                  3049
Significant_Damage_And_Serious_Injuries    2729
Minor_Damage_And_Injuries                  2527
Significant_Damage_And_Fatalities          1695
Name: Severity, dtype: int64

In [23]:
d1.isna().any()

Severity                   False
Safety_Score               False
Days_Since_Inspection      False
Total_Safety_Complaints    False
Control_Metric             False
Turbulence_In_gforces      False
Cabin_Temperature          False
Accident_Type_Code         False
Max_Elevation              False
Violations                 False
Adverse_Weather_Metric     False
Accident_ID                False
dtype: bool

In [38]:
test.isna().any()

Safety_Score               False
Days_Since_Inspection      False
Total_Safety_Complaints    False
Control_Metric             False
Turbulence_In_gforces      False
Cabin_Temperature          False
Accident_Type_Code         False
Max_Elevation              False
Violations                 False
Adverse_Weather_Metric     False
Accident_ID                False
dtype: bool

In [ ]:
#label encoding target variable

In [98]:
from sklearn.preprocessing import  LabelEncoder

In [99]:
le = LabelEncoder()

In [100]:
d1['Severity'] = le.fit_transform(d1['Severity'])

In [101]:
d1['Severity'].value_counts()

0    3049
3    2729
1    2527
2    1695
Name: Severity, dtype: int64

In [33]:
d1.head()

Severity  Safety_Score  Days_Since_Inspection  Total_Safety_Complaints  \
0         1     49.223744                     14                       22   
1         1     62.465753                     10                       27   
2         2     63.059361                     13                       16   
3         3     48.082192                     11                        9   
4         2     26.484018                     13                       25   

   Control_Metric  Turbulence_In_gforces  Cabin_Temperature  \
0       71.285324               0.272118              78.04   
1       72.288058               0.423939              84.54   
2       66.362808               0.322604              78.86   
3       74.703737               0.337029              81.79   
4       47.948952               0.541140              77.16   

   Accident_Type_Code  Max_Elevation  Violations  Adverse_Weather_Metric  \
0                   2   31335.476824           3                0.424352   
1                   2   26024.711057           2                0.352350   
2                   7   39269.053927           3                0.003364   
3                   3   42771.499200           1                0.211728   
4                   3   35509.228515           2                0.176883   

   Accident_ID  
0         7570  
1        12128  
2         2181  
3         5946  
4         9054

In [ ]:
#dropping uniqe accident ID in both test and train data

In [102]:
from sklearn.model_selection import train_test_split

In [103]:
y = d1['Severity']
X = d1.drop('Severity', axis=1)

In [104]:
# split X and y into training and testing sets

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=0)

In [105]:
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import mean_squared_error, accuracy_score, classification_report
from sklearn.metrics import f1_score, confusion_matrix, recall_score, r2_score

In [50]:
#logistic regression:

In [106]:
model = LogisticRegression()

model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [107]:
#predict model
y_pred = model.predict(test)

In [108]:
cm = confusion_matrix(y_test,y_pred)
print('confusion matrix:', cm)

confusion matrix: [[314 258  36 146]
 [273 212  27 115]
 [191 129  28  69]
 [312 212  43 135]]


In [58]:
print('accuracy', accuracy_score(y_test, y_pred))

accuracy 0.2756


In [59]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.29      0.42      0.34       754
           1       0.26      0.34      0.29       627
           2       0.21      0.07      0.10       417
           3       0.29      0.19      0.23       702

   micro avg       0.28      0.28      0.28      2500
   macro avg       0.26      0.25      0.24      2500
weighted avg       0.27      0.28      0.26      2500



# improved accuracy

In [109]:
lr = LogisticRegression(solver='liblinear').fit(X_train, y_train)
 
# Predict on training set
lr_pred = lr.predict(X_test)

In [110]:
# Checking accuracy
accuracy_score(y_test, lr_pred)

0.5268

In [64]:
print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

           0       0.56      0.82      0.66       754
           1       0.51      0.66      0.57       627
           2       0.10      0.04      0.05       417
           3       0.63      0.39      0.48       702

   micro avg       0.53      0.53      0.53      2500
   macro avg       0.45      0.48      0.44      2500
weighted avg       0.49      0.53      0.49      2500



### using newton-cg  as Prediction variable is a multiclass

In [111]:
lr = LogisticRegression(solver='lbfgs').fit(X_train, y_train)
 
# Predict on training set
lr_pred = lr.predict(X_test)

In [112]:
# Checking accuracy
accuracy_score(y_test, lr_pred)

0.5392

In [77]:
print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

           0       0.56      0.81      0.66       754
           1       0.54      0.68      0.60       627
           2       0.14      0.06      0.08       417
           3       0.65      0.40      0.50       702

   micro avg       0.54      0.54      0.54      2500
   macro avg       0.47      0.49      0.46      2500
weighted avg       0.51      0.54      0.50      2500



In [ ]:
### using other hyperparameter tuning 

In [113]:
lr = LogisticRegression(solver='newton-cg').fit(X_train, y_train)
 
# Predict on training set
lr_pred = lr.predict(X_test)

In [114]:
# Checking accuracy
accuracy_score(y_test, lr_pred)

0.5968

In [ ]:
#replace orignal string to feature 'Severity' by Inverse transform

In [118]:
print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

           0       0.64      0.82      0.72       754
           1       0.58      0.70      0.64       627
           2       0.37      0.23      0.28       417
           3       0.65      0.49      0.56       702

   micro avg       0.60      0.60      0.60      2500
   macro avg       0.56      0.56      0.55      2500
weighted avg       0.58      0.60      0.58      2500



In [129]:
df_sub1['Severity'].value_counts()

0    963
1    756
3    524
2    257
Name: Severity, dtype: int64

In [120]:
df_sub1['Severity'].shape

(2500,)

In [130]:
df_sub1=pd.DataFrame(lr_pred,columns=['Severity'])
df_sub1['Accident_ID']=test.Accident_ID

In [122]:
df_sub1.shape

(2500, 2)

In [131]:
df_sub1.to_csv('Predictions_new.csv',index=False)